import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const root=document.getElementById('webgl');
const scene=new THREE.Scene();
scene.fog=new THREE.FogExp2(0x02040d,.018);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,1000);
camera.position.set(0,3.2,13);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.035;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=18;controls.minPolarAngle=.75;controls.maxPolarAngle=1.95;controls.autoRotate=true;controls.autoRotateSpeed=.32;
scene.add(new THREE.HemisphereLight(0x9db8ff,0x10101c,1.6));
const gold=new THREE.PointLight(0xd8b56a,55,35);gold.position.set(0,6,4);scene.add(gold);
const moon=new THREE.DirectionalLight(0x8da8ff,2.2);moon.position.set(-8,12,8);scene.add(moon);
const group=new THREE.Group();scene.add(group);
const starsGeo=new THREE.BufferGeometry(),count=2600,pos=new Float32Array(count*3),sizes=new Float32Array(count);for(let i=0;i<count;i++){const r=12+Math.random()*18,a=Math.random()*Math.PI*2,y=(Math.random()-.15)*14;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=y;pos[i*3+2]=Math.sin(a)*r;sizes[i]=Math.random()*2+0.5}starsGeo.setAttribute('position',new THREE.BufferAttribute(pos,3));starsGeo.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));const stars=new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xd8b56a,size:.055,transparent:true,opacity:.85,sizeAttenuation:true}));scene.add(stars);
function mat(color,rough=.5,metal=.1){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})}
const water=new THREE.Mesh(new THREE.CylinderGeometry(4.8,5.1,.28,96),mat(0x0b3c52,.16,.45));water.position.set(0,-1.8,0);group.add(water);
const poolRing=new THREE.Mesh(new THREE.TorusGeometry(5,.08,12,128),new THREE.MeshBasicMaterial({color:0xd8b56a,transparent:true,opacity:.55}));poolRing.position.copy(water.position);poolRing.rotation.x=Math.PI/2;group.add(poolRing);
const island=new THREE.Mesh(new THREE.CylinderGeometry(3.4,3.8,1.1,64),mat(0x17271e,.9,0));island.position.y=-1.35;group.add(island);
const castle=new THREE.Group();
function tower(x,z,s=1){const t=new THREE.Mesh(new THREE.CylinderGeometry(.38*s,.55*s,2.8*s,16),mat(0xeee6d0,.65,.05));t.position.set(x,.25,z);castle.add(t);const roof=new THREE.Mesh(new THREE.ConeGeometry(.58*s,1.2*s,16),mat(0x233a67,.35,.25));roof.position.set(x,1.95*s-.25,z);castle.add(roof)}
tower(0,0,1.25);tower(-1.65,.15,.75);tower(1.65,.15,.75);tower(-.8,.5,.55);tower(.8,.5,.55);const hall=new THREE.Mesh(new THREE.BoxGeometry(2.3,2.2,1.3),mat(0xd9c99f,.7));hall.position.set(0,-.25,.35);castle.add(hall);group.add(castle);
const moonMesh=new THREE.Mesh(new THREE.SphereGeometry(1.15,32,32),new THREE.MeshStandardMaterial({color:0xffedc4,emissive:0x6b5224,emissiveIntensity:1.4}));moonMesh.position.set(-6,7,-5);scene.add(moonMesh);
const ring=new THREE.Mesh(new THREE.TorusGeometry(1.7,.018,8,96),new THREE.MeshBasicMaterial({color:0xd8b56a,transparent:true,opacity:.65}));ring.position.copy(moonMesh.position);ring.rotation.set(.7,.2,.4);scene.add(ring);
const waves=[];for(let i=0;i<18;i++){const g=new THREE.Mesh(new THREE.TorusGeometry(1.2+i*.18,.012,6,64),new THREE.MeshBasicMaterial({color:0x63d6df,transparent:true,opacity:.18}));g.rotation.x=Math.PI/2;g.position.y=-1.6;g.scale.z=.7;waves.push(g);group.add(g)}
const floating=[];for(let i=0;i<90;i++){const g=new THREE.Mesh(new THREE.IcosahedronGeometry(.025+Math.random()*.06,1),new THREE.MeshBasicMaterial({color:0xd8b56a,transparent:true,opacity:.35+Math.random()*.5}));g.position.set((Math.random()-.5)*13,Math.random()*7-2,(Math.random()-.5)*9);g.userData={speed:.2+Math.random()*.7,phase:Math.random()*6};scene.add(g);floating.push(g)}
const pointer={x:0,y:0};addEventListener('pointermove',e=>{pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight*2-1);document.querySelector('.cursor-dot').style.left=e.clientX+'px';document.querySelector('.cursor-dot').style.top=e.clientY+'px'});
const dot=document.querySelector('.cursor-dot'),cursor=document.querySelector('.cursor-ring');let cx=0,cy=0;function cursorLoop(){cx+=(pointer.x*innerWidth/2+innerWidth/2-cx)*.09;cy+=(-pointer.y*innerHeight/2+innerHeight/2-cy)*.09;cursor.style.left=cx+'px';cursor.style.top=cy+'px';requestAnimationFrame(cursorLoop)}cursorLoop();document.querySelectorAll('a,.card').forEach(e=>{e.addEventListener('pointerenter',()=>cursor.classList.add('active'));e.addEventListener('pointerleave',()=>cursor.classList.remove('active'))});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));addEventListener('scroll',()=>document.querySelector('.nav').classList.toggle('scrolled',scrollY>30),{passive:true});
let clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();controls.update();group.rotation.y+=.0009;castle.rotation.y=Math.sin(t*.25)*.08;water.material.emissive=new THREE.Color(0x062d3d);water.material.emissiveIntensity=.25+.08*Math.sin(t*1.4);poolRing.scale.setScalar(1+.025*Math.sin(t*1.8));waves.forEach((w,i)=>{w.scale.x=1+Math.sin(t*1.4+i*.5)*.035;w.rotation.z=t*.025*(i%2?1:-1)});stars.rotation.y=t*.006;stars.rotation.x=Math.sin(t*.05)*.03;moonMesh.position.y=7+Math.sin(t*.12)*.25;ring.rotation.z=t*.05;floating.forEach(p=>{p.position.y+=Math.sin(t*p.userData.speed+p.userData.phase)*.002;p.rotation.x+=.002;p.rotation.y+=.003});gold.position.x=Math.sin(t*.35)*5;gold.position.z=Math.cos(t*.35)*5;camera.position.x+=(pointer.x*1.3-camera.position.x)*.012;camera.position.y+=(3.2+pointer.y*.7-camera.position.y)*.012;renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))});
addEventListener('load',()=>setTimeout(()=>document.getElementById('loader').classList.add('hide'),700));setTimeout(()=>document.getElementById('loader').classList.add('hide'),2200);